name: CI
on: [push, pull_request]
concurrency:
  group: ci-${{ github.ref }}  # unique per branch
  # cancel previous runs on the same branch, except for master
  cancel-in-progress: ${{ github.ref != 'master' }}
permissions:
  contents: read # to fetch code (actions/checkout)
jobs:
  QEMUv8_check1:
    name: make check (QEMUv8)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Update Git config
        run: git config --global --add safe.directory ${GITHUB_WORKSPACE}
      - name: Restore build cache
        uses: actions/cache@v6
        with:
          path: /home/runner/work/ccache
          key: qemuv8_check-cache-${{ github.sha }}
          restore-keys: |
            qemuv8_check-cache-
      - name: Check
        shell: bash
        run: |
          docker run --rm \
            -v /home/runner/work/optee_ftpm/optee_ftpm:/runner/optee_ftpm \
            -v /home/runner/work/ccache:/root/.cache/ccache \
            -w /root \
            jforissier/optee_os_ci:qemu_check \
            bash -c '
              set -e -v

              export LC_ALL=C
              export BR2_CCACHE_DIR=/root/.cache/ccache
              export FORCE_UNSAFE_CONFIGURE=1
              export CFG_TEE_CORE_LOG_LEVEL=0
              OPTEE_FTPM_TO_TEST=/runner/optee_ftpm
              cd ..
              TOP=/root/optee_repo_qemu_v8
              /root/get_optee.sh qemu_v8 ${TOP}
              mv ${TOP}/optee_ftpm ${TOP}/optee_ftpm_old
              ln -s ${OPTEE_FTPM_TO_TEST} ${TOP}/optee_ftpm
              cd ${TOP}/build

              make -j$(nproc) check MEASURED_BOOT_FTPM=y CHECK_TESTS=xtest XTEST_ARGS=regression_1041
            '
